### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by eritpchy** [kenvix/ComplexBot#13]
加个无脑关键字拦截呗, 那个Ai拦截我就没见成功过~

**Comment by kenvix** [comment]
你好，
机器学习拦截需要自行训练模型。

另外，现有模型效果较差，新模型的一些草稿我放在Jupyternotebook了，可以完善一下。

**Comment by kenvix** [comment]
加关键字本身并非难题，我一直在考虑的是如何设计，使得InspectorRule和Punishment可以提供设置选项，以为用户提供Rule和Punishment相关配置功能。

**Comment by eritpchy** [comment]
> 你好，
> 机器学习拦截需要自行训练模型。
> 
> 另外，现有模型效果较差，新模型的一些草稿我放在Jupyternotebook了，可以完善一下。

是的, 我训练了不过效果一般~ 我群不多, 收集那么多广告毕竟是个很麻烦的事

**Comment by eritpchy** [comment]
> 加关键字本身并非难题，我一直在考虑的是如何设计，使得InspectorRule和Punishment可以提供设置选项，以为用户提供Rule和Punishment相关配置功能。

建议私聊机器人, 可以提供批量设置的选项, 我第一次设置都吐血了, 后面直接操作数据库

**Comment by eritpchy** [comment]
> 加关键字本身并非难题，我一直在考虑的是如何设计，使得InspectorRule和Punishment可以提供设置选项，以为用户提供Rule和Punishment相关配置功能。

当然也可以提供个管理后台修改数据库
或者提供restful接口然后用管理后台操作
