### ISSUE TITLE
众多问题.

### ISSUE THREAD

**Issue by eritpchy** [kenvix/ComplexBot#3]
问题我都改到我的github上了, 参考https://github.com/eritpchy/ComplexBot
开发环境 macOS Catalina 10.15.6 + java 11
生产环境 
OpenJDK 64-Bit Server VM 11.0.8+10 (Oracle Corporation)
PyBotBackend v0.5 @ Python 3.7.9
Platform: Linux | Kotlin 1.4.0

1. 缺少文档
2. System.getProperties()无效的, System.getProperty才行
3. requirements依赖过多
4. java启动backend时, com.kenvix.complexbot.ComplexBotDriver#loadBackend$KMiraiBot_main函数卡死, 类似的问题我在多个软件和操作系统上都碰到过, 不好解决, 最好单独运行
5. 缺少sample配置文件

**Comment by kenvix** [comment]
你好，上述问题实际上都是已知问题，因个人时间原因无暇修复。欢迎您提交 Pull Request 解决

**Comment by eritpchy** [comment]
晚点有空再弄, 先关了
